### ISSUE TITLE
Catmaid access

### ISSUE THREAD

**Issue by orloff18** [CRBS/CIL_PHP_Website#117]
After implementing Catmaid for EM images we need to determine who g\has the ability to draw polygons on the images. 

1. Open access to all 
2. Access only to those who have registered and logged in (ideally with the ability to remove all of there edits if we find they are abusing the service). 
3. Only to those who request it. 

Need to finalize approach when we get closer to implementation. 

I do not think we need to give open access to all. Maybe start with approach 3 until we can determine how to remove all edits from a particular user, then we can implement approach 2.

**Comment by wawong** [comment]
We've decided not to use the Catmaid  server.
