### ISSUE TITLE
Correct typo

### ISSUE THREAD

**Issue by orloff18** [CRBS/CIL_PHP_Website#120]
Please correct typo in description of http://www.cellimagelibrary.org/images/38810

Scanning electron micrograph of a a cluster of breast cancer cells showing visual evidence of programmed cell death (apoptosis) in yellow. Each cell is 15 micrometers across.

There should only be one a in  "of a a cluster of breast cancer"

**Comment by thecatsinn** [comment]
Fixed.

**Comment by wawong** [comment]
Fixed.
