### ISSUE TITLE
Errors in Eukaryotic Cell Interactive Image

### ISSUE THREAD

**Issue by orloff18** [CRBS/CIL_PHP_Website#142]
Golgi Apparatus - returns results for paramecium cytopharynx and no subimage and i am pretty sure there should be one.
Mitochondrion - shows image of mitochondrion but says Microtubule organising centers - subimage has no interaction animation
Molecular Machinery - missing (did we have? - not sure)
Ribosome returns results for molecular machinery and ribosome illustration missing

**Comment by wawong** [comment]
We don't have the Molecular Machinery option for the Eukaryotic Cell Interactive Image. The other problems should have been fixed.
